### PR TITLE
fix #1451

### LINKED ISSUE #1451: buildparameter forget add paramNameList
## Describe the bug

When the parameter is one and the type starts with “java”， 500 will be reported
image

When i debug,  i find this medthod has problem
org.apache.shenyu.plugin.api.utils.BodyParamUtils#buildParameters 

we can see paramNameList.size() = 0, it cause param's value is null
image
image

add some code in org.apache.shenyu.plugin.api.utils.BodyParamUtils#buildParameters  can fix it

image

### PR DESCRIPTION
**Pull request by Ting97**
add parameName to paramNameList

// Describe your PR here; eg. Fixes #issueNo
fix #1451 add parameName to paramNameList 

Make sure that:

- [x] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java [hunk 1]
```diff
@@ -72,26 +71,26 @@
             paramNameList.addAll(paramNameMap.keySet());
             paramTypeList.addAll(paramNameMap.values());
         } else {
-            paramTypeList = Arrays.asList(StringUtils.split(parameterTypes, ","));
+            Map<String, Object> paramMap = GsonUtils.getInstance().toObjectMap(body);
+            paramNameList.addAll(paramMap.keySet());
```
Comment (KevinClair) [inline shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java:75]: Repeat code, you should refactor it.

Comment (tydhot) [inline shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java:75]: It seemed that keyset will be added anyway

Comment (Ting97) [reply shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java:75]: There is different map.keyset  to added paramNameList
