### PR TITLE
fix #1478

### LINKED ISSUE #1478: NacosClientRegisterRepository#persistInterface occurs NPE when the value of port is null
## Describe the bug

NacosClientRegisterRepository#persistInterface occurs NPE when the value of port is null ,so Integer auto-unboxing  occurs NPE. I found that  in ContextRegisterListener#buildMetaDataDTO  method missing the parameter of port.
## Environment

- Soul version(s): 2.3.0-RELEASE

## Steps to reproduce
Exception in thread "soul-disruptor-soul_disruptor_consumer_-17" java.lang.NullPointerException
	at org.dromara.soul.register.client.nacos.NacosClientRegisterRepository.persistInterface(NacosClientRegisterRepository.java:84)
	at org.dromara.soul.client.core.disruptor.subcriber.SoulClientMetadataExecutorSubscriber.executor(SoulClientMetadataExecutorSubscriber.java:53)
	at org.dromara.soul.client.core.disruptor.executor.RegisterClientConsumerExecutor.run(RegisterClientConsumerExecutor.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

### PR DESCRIPTION
**Pull request by joewee**
fix #1478

Make sure that:

- [X] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java [hunk 1]
```diff
@@ -88,10 +89,14 @@ public void onApplicationEvent(@NonNull final ContextRefreshedEvent contextRefre
     private MetaDataRegisterDTO buildMetaDataDTO() {
         String contextPath = this.contextPath;
         String appName = env.getProperty("spring.application.name");
+        Integer port = env.getProperty("server.port",Integer.class,8080);
+        String host = NetUtils.localIP();
```
Comment (yu199195) [inline shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java:93]: can not used this NetUtils.localIP();

File: shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java [hunk 2]
```diff
@@ -17,6 +17,7 @@
 
 package org.apache.shenyu.client.springcloud.init;
 
+import com.alibaba.nacos.api.utils.NetUtils;
 import lombok.extern.slf4j.Slf4j;
```
Comment (tydhot) [inline shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java:21]: I think is a bad idea to use nacos's util here.

**Review by tydhot — CHANGES_REQUESTED** [review]

File: shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java (hunk 2 above)
Comment (joewee) [reply shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java]: Yes, you are right, i should  use org.apache.shenyu.common.utils.IpUtils.getHost() instead of using NetUtils.localIP(), right?

File: shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java [hunk 3]
```diff
@@ -88,10 +89,14 @@ public void onApplicationEvent(@NonNull final ContextRefreshedEvent contextRefre
     private MetaDataRegisterDTO buildMetaDataDTO() {
         String contextPath = this.contextPath;
         String appName = env.getProperty("spring.application.name");
+        Integer port = env.getProperty("server.port",Integer.class,8080);
```
Comment (yu199195) [inline shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java:92]: maybe here，  ","  need  blank space after  it.....

**Comment by yu199195** [comment]
please check ci。。。。
