### PR TITLE
Fix java.lang.ClassCastException when saveOrUpdateMetaData

### LINKED ISSUE #1231: 2.3.0 soul admin java.lang.ClassCastException bug
## Describe the bug
in 2.3.0 admin soul , when MetaData be push, have a  java.lang.ClassCastException: org.dromara.soul.admin.entity.MetaDataDO cannot be cast to org.dromara.soul.common.dto.MetaData

## Environment

- Soul version(s): [e.g. 2.3.0]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

### PR DESCRIPTION
**Pull request by zhangjh**
// Describe your PR here; eg. Fixes #1231 
In class `org.apache.shenyu.admin.service.impl.ShenyuClientRegisterServiceImpl`, when register subbo,sofa,tars,etc...the function `saveOrUpdateMetaData` will be called.
The event publisher will publish an event at the last of this function. And the published event pass the parameter by 
```java
new DataChangedEvent(ConfigGroupEnum.META_DATA, eventType,
                Collections.singletonList(MetaDataTransfer.INSTANCE.mapRegisterDTOToEntity(metaDataDTO)))
```
that will build a `MetaDataDO`  to `DataChangedEvent`.
Then the event listener `ZookeeperDataChangedListener` will exception when call method `onMetaDataChanged`, cause that the received parameter is `MetaData`.

### CODE REVIEW

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuClientRegisterServiceImpl.java [hunk 1]
```diff
@@ -341,7 +341,8 @@ private void saveOrUpdateMetaData(final MetaDataDO exist, final MetaDataRegister
         }
         // publish MetaData's event
         eventPublisher.publishEvent(new DataChangedEvent(ConfigGroupEnum.META_DATA, eventType,
-                Collections.singletonList(MetaDataTransfer.INSTANCE.mapRegisterDTOToEntity(metaDataDTO))));
+                Collections.singletonList(MetaDataTransfer.INSTANCE.mapToData(
+                        MetaDataTransfer.INSTANCE.mapRegisterDTOToEntity(metaDataDTO)))));
```
Comment (yu199195) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuClientRegisterServiceImpl.java:345]: is used MetaDataTransfer.INSTANCE.mapToData(metaDataDO)),

Although there are type errors here, they do not lead to generic exception in   DataChangedEventDispatcher  like this  

```
 case META_DATA:
                    listener.onMetaDataChanged((List<MetaData>) event.getSource(), event.getEventType());
```

**Review by yu199195 — APPROVED** [review]

**Review by dengliming — APPROVED** [review]
